# experiment name
EXP_NAME: stargan_celeba256
# random number seed
SEED: 42
# run device model
DEVICE_ID: 0

# Model define
MODEL:
  G:
    C_DIM: 5
    COMPILED: True
  D:
    IMG_SIZE: 256
    C_DIM: 5
    COMPILED: False

DATASETS:
  IMGS_DIR: "./data/celeba/images"
  CROP_IMG_SIZE: 178
  RESIZE_IMG_SIZE: 256
  ATTR_PATH: "./data/celeba/list_attr_celeba.txt"
  SELECTED_ATTRS: ["Black_Hair", "Blond_Hair", "Brown_Hair", "Male", "Young"]

TRAIN:
  # Model file address, used for pre-training and recovery training
  CHECKPOINT:
    G:
      PRETRAINED_MODEL_WEIGHTS_PATH: ""
      RESUME_MODEL_WEIGHTS_PATH: ""
    D:
      PRETRAINED_MODEL_WEIGHTS_PATH: ""
      RESUME_MODEL_WEIGHTS_PATH: ""

  # training hyperparameters
  HYP:
    IMGS_PER_BATCH: 16

    EPOCHS: 16

  OPTIM:
    G:
      LR: 0.0001
      BETA1: 0.5
      BETA2: 0.999
      WEIGHT_DECAY: 0.00005
    D:
      LR: 0.0001
      BETA1: 0.5
      BETA2: 0.999
      WEIGHT_DECAY: 0.00005

  LR_SCHEDULER:
    G:
      STEP_SIZE: 8
      GAMMA: 0.5
    D:
      STEP_SIZE: 8
      GAMMA: 0.5

  # Loss function
  LOSSES:
    CLASS_LOSS:
      WEIGHT: [ 1.0 ]
    GP_LOSS:
      WEIGHT: [ 10.0 ]
    REC_LOSS:
      WEIGHT: [ 10.0 ]

  N_CRITIC: 5  # Update D every n_critic iterations

  PRINT_FREQ: 100
  VISUAL_FREQ: 1000
  SAVE_EVERY_EPOCH: False

TEST:
  # Model file address, used for pre-training and recovery training
  CHECKPOINT:
    MODEL_WEIGHTS_PATH: "./results/pretrained_models/g_celeba256.pth.tar"
  HYP:
    IMGS_PER_BATCH: 1